/*var days=["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
var monthList=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
var now=new Date();
var weekDays=days[now.getDay()];
var date= now.getDate();
var month=monthList[now.getMonth()];
var year=now.getFullYear();
var fullDate= weekDays + "," +" " + month + " " + date + "," + " " + year;
document.getElementById('currentDate').textContent=fullDate;*/
var dateNow=new Date(document.lastModified);
document.getElementById('currentDate').textContent=dateNow;
